steps:
- name: "gcr.io/kaniko-project/executor:v1.6.0"
  args: ["--cache=true", "--cache-ttl=48h", "--dockerfile=/Docker/staging.Dockerfile", "--destination=gcr.io/$PROJECT_ID/marlonadmin-staging:latest"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy deployConfig/app_staging.yml --image-url gcr.io/$PROJECT_ID/marlonadmin-staging:latest']
timeout: '1600s'
options:
  machineType: 'N1_HIGHCPU_32'
