export const resumeAIConstants = {
    GET_CONVERSION_RATE_REQUEST : 'GET_CONVERSION_RATE_REQUEST',
    GET_CONVERSION_RATE_SUCCESS : 'GET_CONVERSION_RATE_SUCCESS', 
    GET_CONVERSION_RATE_FAILURE : 'GET_CONVERSION_RATE_FAILURE',
}