export const authConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

    SAVE_REQUEST: 'SAVE_REQUEST',
    SAVE_FAILURE: 'SAVE_FAILURE',
    SAVE_SUCCESS: 'SAVE_SUCCESS',

    LOGOUT: 'LOGOUT',

    IAP_SELF_REQUEST: 'IAP_SELF_REQUEST',
    IAP_SELF_FAILURE: 'IAP_SELF_FAILURE',
    IAP_SELF_SUCCESS: 'IAP_SELF_SUCCESS'
}