export const botLogConstants = { 
    GET_ALL_BOT_LOGS_REQUEST : 'GET_ALL_BOT_LOGS_REQUEST',
    GET_ALL_BOT_LOGS_SUCCESS : 'GET_ALL_BOT_LOGS_SUCCESS', 
    GET_ALL_BOT_LOGS_FAILURE : 'GET_ALL_BOT_LOGS_FAILURE',
}