export const unsupJobConstants = { 
    GET_UNSUP_JOB_REQUEST : 'GET_UNSUP_JOB_REQUEST',
    GET_UNSUP_JOB_SUCCESS : 'GET_UNSUP_JOB_SUCCESS', 
    GET_UNSUP_JOB_FAILURE : 'GET_UNSUP_JOB_FAILURE',

    GET_ALL_UNSUP_JOB_REQUEST : 'GET_ALL_UNSUP_JOB_REQUEST',
    GET_ALL_UNSUP_JOB_SUCCESS : 'GET_ALL_UNSUP_JOB_SUCCESS', 
    GET_ALL_UNSUP_JOB_FAILURE : 'GET_ALL_UNSUP_JOB_FAILURE',
}